[build]
  base = "Lucky Learning"
  publish = "dist/client"
  command = "npm install && npm run build"
[build]
  command = "vite build"
  publish = "dist/client
[[plugins]]
package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "your-cloud-name"
  imagesPath = "/your/actual/
